### ISSUE TITLE
Support custom `paths` to clean up

### ISSUE THREAD

**Issue by Saviq** [mickem/clean-after-action#1]
It would be nice for the action to support [cache](https://github.com/actions/cache)-like `path` as input:

```yaml
- uses: mickem/clean-after-action@v1
  with:
    paths:
    - .
    - !.git
```
